# Generated by Django 2.2.4 on 2020-01-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='show',
            name='time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='venue_url',
            field=models.URLField(default='09:00'),
            preserve_default=False,
        ),
    ]
